apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yolo
  template:
    metadata:
      labels:
        app: yolo
    spec:
      containers:
      - name: frontend
        image: gcr.io/yolo-deploy-425312/yolo-frontend:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
      - name: backend
        image: gcr.io/yolo-deploy-425312/yolo-backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: MONGODB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mongodb-config
              key: database
        - name: MONGODB_HOST
          valueFrom:
            configMapKeyRef:
              name: mongodb-config
              key: host
        - name: MONGODB_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: username
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: password
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1"

---

apiVersion: v1
kind: Service
metadata:
  name: yolo-service
spec:
  type: LoadBalancer
  selector:
    app: yolo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80