version: "3.8"

services:
  frontend:
    build: 
      context: ./client
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_URL=http://backend:5000
    networks:
      - yolo-net
    depends_on:
      - backend
    image: marvol0/yolo-frontend:v2.0.0

  backend:
    build: 
      context: ./backend
    ports:
      - "5000:5000"
    env_file:
      - /workspaces/yolo/backend/.env
    environment:
      - MONGO_URI=mongodb://admin:password@moringa-week-4-cluster.kcbekzb.mongodb.net/?retryWrites=true&w=majority&appName=moringa-week-4-cluster
    networks:
      - yolo-net
    depends_on:
      - mongodb
    image: marvol0/yolo-backend:v1.0.0
    restart: always

  mongodb:
    image: mongo:latest
    container_name: mongodb
    env_file:
      - /workspaces/yolo/backend/.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - yolo-net

networks: 
  yolo-net:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
