version: "3.8"

services:
  backend:
    build: 
      context: ./backend
    ports:
      - "4567:4567"
    volumes:
      - ./backend:/app
    networks:
      - yolo-net
    depends_on:
      - mongodb

  frontend:
    build: 
      context: ./client
    ports:
      - "3000:3000"
    networks:
      - yolo-net
    volumes:
      - ./client:/app
    depends_on:
      - backend

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - yolo-net

networks: 
  yolo-net:
    #driver: bridge
    #name: yolo-net
    external: true

volumes:
  mongodb_data:
    driver: local
