version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "4567:4567"
    volumes:
      - ./backend
    networks:
      - yolo-net
  frontend:
    build: ./client
    ports:
      - "3000:3000"
    networks:
      - yolo-net
    volumes:
      - ./client
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: Marvin
      MONGO_INITDB_ROOT_PASSWORD: test123
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

networks: 
  cruddur-net:
    driver: bridge
    name: yolo-net

volumes:
  db:
    driver: local
