---

- hosts: all
  become: true
  vars_files:
    - vars/main.yml

  roles:
    - common
    - frontend-config
    - backend-config
    - docker-config
    - mongodb-config

  tasks:
    - name: Clone repository
      git:
        repo: "{{ github_repo }}"
        dest: "{{ app_dir }}"
        update: yes
      tags: cloned

    
