- hosts: all
  become: true
#  tasks:
#    - name: Install Dependencies
#      apt:
#        name: python3-pip
#        state: present
#    - name: Install Docker Pyhton SDK
#      pip:
#        name: docker
#        state: present 
#    - name: Clone repository
#      git:
#        repo: "{{ github_repo }}"
#        update: yes
#        force: yes
#        clone: yes
#        version: master
  roles:
    - frontend-config
    - backend-config
    - common
    - docker-config