apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  username: bWFydmlu   # base64 encoded value of 'mongo_user'
  password: dGVzdDEyMw==  # base64 encoded value of 'secret_password'
