apiVersion: v1
kind: Service
metadata:
  name: yolo-frontend-service
spec:
  selector:
    app: yolo
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: yolo-backend-service
spec:
  selector:
    app: yolo
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
