---

- name: update apt cache
  apt: update_cache=yes


- name: install necessary packages for apt to use 
  apt: 
    pkg:
      - git
      - curl
      - apt-transport-https
      - python3-pip
      - python3-venv
    state: present
  tags: install_packages



