---
- name: setup docker
  block:
  - name: Install docker-ce and docker-compose
    apt: 
      pkg:
        - docker-ce
        - docker-compose
      install_recommends: yes
      state: present 

  - name: add users to the Docker group
    user:
      name: "{{ system_user }}"
      groups: docker
      append: yes

  - name: add vagrant user to docker group
    user: 
      name: "{{ vagrant_user }}"
      groups: docker
      append: yes

  tags: setup_docker
