---

- name: frontend setup
  block:
    - name: check app directory exists
      file: 
        path: "{{ frontend_app_directory }}"
        state: directory

    - name: clone frontend application
      git: 
        repo: "{{ github_repo }}"
        dest: "{{ frontend_app_directory }}"
        update: yes
      tags: clone_repo

    - name: Install Dependencies
      apt:
        name: python3-pip
        state: present

- name: Build and run docker container
  docker_compose:
    project_src: "{{ docker_compose_directory }}"
    state: present

- name: check application is running
  uri: 
    url: "http:localhost:3000"
    return_content: yes
    status_code: 200
  register: result
  retries: 5
  delay: 10
  until: result.status == 200
  tags: verify_application
